# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'Duhigg' do
pod 'SDWebImage', '~>3.6'
pod 'SWTableViewCell', '~> 0.3.6'

end

target 'DuhiggTests' do

end

